prefix		= /usr/local/src/SAOImageDS9
exec_prefix	= /usr/local/src/SAOImageDS9

bindir		= ${exec_prefix}/bin
libdir		= $(exec_prefix)/lib
#libdir		= /usr/local/src/SAOImageDS9/lib
includedir	= ${prefix}/include
datarootdir	= ${prefix}/share
datadir		= ${datarootdir}
mandir		= ${datarootdir}/man

TCLSH_PROG	= /usr/local/src/SAOImageDS9/tcl8.6/unix/tclsh

TCL_VERSION	= 8.6
TCL_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tcl8.6/unix -ltcl8.6
TCL_STUB_LIB_SPEC= -L/usr/local/src/SAOImageDS9/tcl8.6/unix -ltclstub8.6
TK_LIBS		= -lX11 -lXft -lfontconfig -lfreetype -lfontconfig  -lpthread -ldl -lz  -lpthread -lm
TK_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tk8.6/unix -ltk8.6
TK_STUB_LIB_SPEC= -L/usr/local/src/SAOImageDS9/tk8.6/unix -ltkstub8.6

util_LIB_SPEC= -L/usr/local/src/SAOImageDS9/util -lutil1.0
vector_LIB_SPEC= -L/usr/local/src/SAOImageDS9/vector -lvector1.0
fitsy_LIB_SPEC= -L/usr/local/src/SAOImageDS9/fitsy -lfitsy1.0

tifftcl_LIB_SPEC= -L/usr/local/src/SAOImageDS9/lib/tifftcl4.1.0 -ltifftcl4.1.0
jpegtcl_LIB_SPEC= -L/usr/local/src/SAOImageDS9/lib/jpegtcl9.4.0 -ljpegtcl9.4.0
zlibtcl_LIB_SPEC= -L/usr/local/src/SAOImageDS9/lib/zlibtcl1.2.11 -lzlibtcl1.2.11

tkimg_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/lib/tkimg1.4.13 -ltkimg1.4.13
tkimgjpeg_LIB_SPEC= -L/usr/local/src/SAOImageDS9/lib/tkimgjpeg1.4.13 -ltkimgjpeg1.4.13
tkimgtiff_LIB_SPEC= -L/usr/local/src/SAOImageDS9/lib/tkimgtiff1.4.13 -ltkimgtiff1.4.13
tkimgwindow_LIB_SPEC= -L/usr/local/src/SAOImageDS9/lib/tkimgwindow1.4.13 -ltkimgwindow1.4.13

tcliis_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tcliis -ltcliis1.0
tclfitsy_LIB_SPEC= -L/usr/local/src/SAOImageDS9/tclfitsy -ltclfitsy1.0
tclsignal_LIB_SPEC= -L/usr/local/src/SAOImageDS9/tclsignal -ltclsignal1.4.4.1
tclxml_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tclxml -ltclxml3.2
tclzipfs_LIB_SPEC= -L/usr/local/src/SAOImageDS9/tclzipfs -ltclzipfs1.0
tls_LIB_SPEC	=-L/usr/local/src/SAOImageDS9/tls -ltls1.6.7

tkblt_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tkblt -ltkblt3.2
tkhtml1_LIB_SPEC= -L/usr/local/src/SAOImageDS9/tkhtml1 -ltkhtml11.0
tkmpeg_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tkmpeg -ltkmpeg1.0
tksvg_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tksvg -ltksvg0.7
tkagif_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tkagif -ltkagif1.0
tksao_LIB_SPEC	= -L/usr/local/src/SAOImageDS9/tksao -ltksao1.0
tktable_LIB_SPEC= -L/usr/local/src/SAOImageDS9/tktable -ltktable2.10

CC		= gcc
CXX		= g++
CFLAGS_DEFAULT	= -g
CFLAGS_WARNING	= -Wall
EXEEXT		= 
OBJEXT		= o

INCLUDES	=  -I/usr/local/src/SAOImageDS9/tk8.6/unix -I"/usr/local/src/SAOImageDS9/tcl8.6/generic" -I"/usr/local/src/SAOImageDS9/tk8.6/generic" 

PKG_CFLAGS	= 
DEFS		= -DPACKAGE_NAME=\"ds9\" -DPACKAGE_TARNAME=\"ds9\" -DPACKAGE_VERSION=\"8.4\" -DPACKAGE_STRING=\"ds9\ 8.4\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DBUILD_ds9=/\*\*/ -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -DSTATIC_BUILD=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\) -DHAVE_HIDDEN=1 -DHAVE_CAST_TO_UNION=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_IS_LONG=1 $(PKG_CFLAGS)

CPPFLAGS	= 
LIBS		=  -L/usr/local/src/SAOImageDS9/lib/tifftcl4.1.0 -ltifftclstub4.1.0 -L/usr/local/src/SAOImageDS9/lib/jpegtcl9.4.0 -ljpegtclstub9.4.0 -L/usr/local/src/SAOImageDS9/lib/zlibtcl1.2.11 -lzlibtclstub1.2.11 -L/usr/local/src/SAOImageDS9/tkblt -ltkbltstub3.2 -L/usr/local/src/SAOImageDS9/lib/tkimg1.4.13 -ltkimgstub1.4.13 -lX11  -lxml2
CFLAGS		=  -pipe ${CFLAGS_DEFAULT} ${CFLAGS_WARNING} 
CXXFLAGS	= -g -O2
COMPILE		= $(CC) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)
COMPILE_CXX	= $(CXX) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)

system		= Linux-5.15.0-69-generic

.SUFFIXES: .c .C .$(OBJEXT)

.c.o:
	$(COMPILE) -c `echo $<` -o $@

.C.o:
	$(COMPILE_CXX) -c `echo $<` -o $@

#--------------------------defines

APPDIR	= mntpt
LIBDIR= $(APPDIR)

ID	= $(shell finger $(shell whoami) | egrep -o 'Name: [a-zA-Z0-9 ]{1,}' | cut -d ':' -f 2 | head -n 1| xargs echo)

OBJS	= ds9.o tkAppInit.o

empty:=
space:=$(empty) $(empty)

SPECS	= \
	$(tcliis_LIB_SPEC) \
	$(tclfitsy_LIB_SPEC) \
	$(tclsignal_LIB_SPEC) \
	$(tclxml_LIB_SPEC) \
	$(tclzipfs_LIB_SPEC) \
	$(tls_LIB_SPEC) \
	$(tkblt_LIB_SPEC) \
	$(tkhtml1_LIB_SPEC) \
	$(tkimg_LIB_SPEC) \
	$(tkimgjpeg_LIB_SPEC) \
	$(tkimgtiff_LIB_SPEC) \
	$(tkimgwindow_LIB_SPEC) \
	$(tkmpeg_LIB_SPEC) \
	$(tksvg_LIB_SPEC) \
	$(tkagif_LIB_SPEC) \
	$(tksao_LIB_SPEC) \
	$(tktable_LIB_SPEC) \
	$(jpegtcl_LIB_SPEC) \
	$(tifftcl_LIB_SPEC) \
	$(zlibtcl_LIB_SPEC) \
	$(fitsy_LIB_SPEC) \
	$(vector_LIB_SPEC) \
	$(util_LIB_SPEC) \
	$(TK_STUB_LIB_SPEC) \
	$(TK_LIB_SPEC) \
	$(TCL_STUB_LIB_SPEC) \
	$(TCL_LIB_SPEC)

LLIBS	= \
	$(subst /$(space),/,$(patsubst -L%,%/,$(patsubst -l%,lib%.a,$(SPECS)))) \
	$(libdir)/libast.a \
	$(libdir)/libast_err.a \
	$(libdir)/libast_pal.a \
	$(libdir)/libast_cminpack.a \
	$(subst /$(space),/,$(patsubst -L%,%/,$(patsubst -l%,lib%.a,$(tksao_LIB_SPEC)))) \
	$(libdir)/libfuntools.a \
	$(libdir)/libxpa.a

PREQS	= \
	$(APPDIR) \
	$(LIBDIR)/tcl$(TCL_VERSION) \
	$(LIBDIR)/tcl8 \
	$(LIBDIR)/tk$(TCL_VERSION) \
	$(LIBDIR)/library \
	$(LIBDIR)/msgs \
	$(LIBDIR)/doc \
	$(LIBDIR)/cmaps \
	$(LIBDIR)/template \
	$(LIBDIR)/icons \
	$(LIBDIR)/tls \
	$(LIBDIR)/tkblt \
	$(LIBDIR)/tkcon \
	$(LIBDIR)/base64 \
	$(LIBDIR)/ftp \
	$(LIBDIR)/log \
	$(LIBDIR)/textutil \
	$(LIBDIR)/math \
	$(LIBDIR)/tooltip \
	$(LIBDIR)/awthemes \
	$(LIBDIR)/ttkthemes \
	$(LIBDIR)/scidthemes

#--------------------------main

.NOTPARALLEL :
.PHONY	: debug

ifeq (,$(findstring Darwin,$(system)))

ds9	: ds9base ds9.zip
	$(RM) ds9
	strip ds9base
	cat ds9base ds9.zip > ds9
	zip -A ds9
	chmod 755 ds9
	cp ds9 $(prefix)/bin/.

debug	: ds9base ds9.zip
	$(RM) ds9
	cat ds9base ds9.zip > ds9
	zip -A ds9
	chmod 755 ds9
	cp ds9 $(prefix)/bin/.

else

ds9	: ds9base ds9.zip
	$(RM) ds9 $(prefix)/bin/ds9 $(prefix)/bin/ds9.zip
	strip ds9base
	cp ds9base ds9
	cp ds9 $(prefix)/bin/.
	cp ds9.zip $(prefix)/bin/.
#	cd $(prefix)/bin; codesign -s "$(ID)" ds9

debug: ds9base ds9.zip
	$(RM) ds9 $(prefix)/bin/ds9 $(prefix)/bin/ds9.zip
	cp ds9base ds9
	cp ds9 $(prefix)/bin/.
	cp ds9.zip $(prefix)/bin/.
#	cd $(prefix)/bin; codesign -s "$(ID)" ds9

endif

ds9base	: $(OBJS) $(LLIBS)
	$(RM) $@
	$(CXX) $(CFLAGS) -o $@ \
	$(OBJS) \
	$(LLIBS) \
	-L $(prefix)/openssl -lssl -lcrypto \
	$(TK_LIBS) \
	$(LIBS)

ds9.zip	: $(PREQS)
	zip -ru ds9.zip $(APPDIR)

tkAppInit.o : tkAppInit.c
	$(COMPILE) -DTK_LOCAL_APPINIT=SAOAppInit \
	-DTK_LOCAL_MAIN_HOOK=SAOLocalMainHook -c $? -o $@

tkAppInit.c : $(prefix)/tk$(TCL_VERSION)/unix/tkAppInit.c
	cp $? .

$(APPDIR) : 
	mkdir -p $@

$(LIBDIR)/tcl$(TCL_VERSION) :
	cp -prf $(prefix)/lib/tcl$(TCL_VERSION) $(LIBDIR)/.

$(LIBDIR)/tcl8 :
	cp -prf $(prefix)/lib/tcl8 $(LIBDIR)/.

$(LIBDIR)/tk$(TCL_VERSION) :
	cp -prf $(prefix)/lib/tk$(TCL_VERSION) $(LIBDIR)/.
	rm -rf $(APPDIR)/tk$(TCL_VERSION)/images
	rm -rf $(APPDIR)/tk$(TCL_VERSION)/demos

#--------------------------awthemes

$(LIBDIR)/awthemes: $(prefix)/awthemes
	cp -prf $? "$@"

#--------------------------ttkthemes

$(LIBDIR)/ttkthemes: $(prefix)/ttkthemes/ttkthemes/themes
	cp -prf $? "$@"

#--------------------------scidthemes

$(LIBDIR)/scidthemes: $(prefix)/scidthemes
	cp -prf $? "$@"

#--------------------------clean

.PHONY	: clean

clean	: parsersclean
	$(RM) core *~ *# ds9base ds9 *.zip *.o
	$(RM) -rf $(APPDIR)

include ../make.include
